FROM goreleaser/goreleaser

LABEL "com.github.actions.name"="GoReleaser"
LABEL "com.github.actions.description"="Deliver Go binaries as fast and easily as possible"
LABEL "com.github.actions.icon"="terminal"
LABEL "com.github.actions.color"="blue"
LABEL "repository"="http://github.com/goreleaser/goreleaser"
LABEL "homepage"="http://goreleaser.com"
LABEL "maintainer"="Carlos Becker <goreleaser@carlosbecker.com>"
